// Builds the MCP App (ui/) into a single self-contained HTML document and
// emits it as src/generated/appHtml.ts, which the server bundles and serves
// as the ui://willhaben/results.html resource.
//
// Run automatically by `npm run build` / `npm run check` / `npm run dev`.

import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const result = await build({
  entryPoints: [join(root, "ui", "app.js")],
  bundle: true,
  minify: true,
  format: "iife",
  target: ["es2020"],
  write: false,
  absWorkingDir: root,
  logLevel: "silent",
});

// Inline scripts must not contain a literal "</script>".
const js = result.outputFiles[0].text.replaceAll("</script>", "<\\/script>");
const css = (await readFile(join(root, "ui", "styles.css"), "utf8")).replaceAll("</style>", "<\\/style>");

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>willhaben results</title>
<style>
${css}
</style>
</head>
<body>
<div id="root"></div>
<script>
${js}
</script>
</body>
</html>
`;

const outDir = join(root, "src", "generated");
await mkdir(outDir, { recursive: true });
await writeFile(
  join(outDir, "appHtml.ts"),
  `// @generated by scripts/build-ui.mjs — do not edit by hand.\n` +
    `// Self-contained MCP App document served as ui://willhaben/results.html\n` +
    `export const RESULTS_APP_HTML: string = ${JSON.stringify(html)};\n`
);

console.log(`build-ui: wrote src/generated/appHtml.ts (${(html.length / 1024).toFixed(0)} KiB)`);
